### ISSUE TITLE
cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by jiangsen** [mhauskn/dqn-hfo#20] opened 2016-04-03 16:25 UTC
Hi Mhauskn:
     I am interested int your research, and I want to rebuild your project dqn-hfo, However when I make the project, error occurred, the compiler says that fetal error cublas_v2.h No such file or directory, I want to know have you meet this problem. And can you give out a document to lead us to learn the project , thx.

**Comment by mhauskn** [comment] 2016-04-03 17:07
Hey! Thanks for your interest in the project. cublas_v2 is typically used by Caffe. Were you able to successfully install Caffe? 

I've updated the project's README with some more detailed instructions for installation. Perhaps they will help?

**Comment by jiangsen** [comment] 2016-04-04 11:55
Thanks for your response, Today I did as your Readme.md file, however the same problem still be there  fetal error cublas_v2.h No such file or directory, meanwhile when I did the operation make -j4 there also be another error,  error: no matching function for call to ‘hfo::HFOEnvironment::connectToServer. I think whether I did not do something configure and this caused the problems. And would you mind give more information(my cuda vision is cuda-7.0) to help me.

**Comment by mhauskn** [comment] 2016-04-04 15:50
DQN-HFO code does not require cublas, only Caffe does. So I suspect you have a problem in your Caffe installation. Particularly, these two threads may help:

https://github.com/BVLC/caffe/issues/2704
https://groups.google.com/forum/#!topic/caffe-users/DAv5EcsvbIU

Can you try `locate cublas_v2.h` to make sure the file exists? If it exists, try adding the path to your $CPLUS_INCLUDE_PATH

**Comment by jiangsen** [comment] 2016-04-05 14:48
Today I rebuild the caffe again,as the follow step:
cp Makefile.config.example Makefile.config(change the cuda path to /usr/local/cuda-7.0)
make all
make test
make runtest
disappointed, It is also does not work, so I want to get the caffe you used, Can you email the caffe you compiled to me, my address is songchongyuan@163.com, and the HFO error is:
/dqn-hfo/hfo_game.cpp: In function ‘void ConnectToServer(hfo::HFOEnvironment&, int, int)’:
dqn-hfo/hfo_game.cpp:46:43: error: no matching function for call to ‘hfo::HFOEnvironment::connectToServer(hfo::feature_set_t, fLS::clstring&, int&, int&, fLS::clstring&, fLS::clstring&, bool&, fLS::clstring&)’
                           FLAGS_record_dir);
                                           ^
dqn-hfo/hfo_game.cpp:46:43: note: candidate is:
In file included from dqn-hfo/hfo_game.hpp:4:0,
                 from dqn-hfo/hfo_game.cpp:3:
/HFO/src/HFO.hpp:30:8: note: void hfo::HFOEnvironment::connectToServer(hfo::feature_set_t, std::string, int, std::string, std::string, bool, std::string)
   void connectToServer(feature_set_t feature_set=HIGH_LEVEL_FEATURE_SET,
        ^
HFO/src/HFO.hpp:30:8: note:   candidate expects 7 arguments, 8 provided
I also think I am wrong with the method to make the dqn_hfo file, Hope you can solve this question, thank you.

**Comment by mhauskn** [comment] 2016-04-05 19:51
I've sent you some instructions for checking out the correct version of Caffe and compiling. 

With regard to the HFO error, it was caused by the dqn-hfo codebase using a slightly out-of-date version of the HFO library. I've updated the code to fix this problem. Please do a `git pull` to get the fix.

**Comment by mhauskn** [comment] 2016-04-06 15:35
In order to fix the cublas error, you will have to include the path to your cuda folder.

1) `locate cublas_v2.h` -- this should give you the path to your cuda installation
2) export CPLUS_INCLUDE_PATH=/your/cuda/path:$CPLUS_INCLUDE_PATH

Your cuda path will look something like: /opt/cuda-7.0/include

Try this and see if the error changes.

**Comment by jiangsen** [comment] 2016-04-07 13:28
Finally, The programm run correctly, thank you for all of your help.

**Comment by mhauskn** [comment] 2016-04-07 14:56
Great! I'll go ahead and close the issue.

**Comment by mrgloom** [comment] 2016-05-16 18:27
Same issue, I get this error when I use CPY_ONLY build  https://github.com/mrgloom/Caffe-snippets/blob/master/Makefile.config and using openblas installed via http://stackoverflow.com/questions/36483054/install-openblas-via-apt-get-sudo-apt-get-install-openblas-dev

I definitely not use CUDA what is the problem?

**Comment by mhauskn** [comment] 2016-05-17 17:57
Can you try requesting cpu-only mode when you build dqn-hfo? You'll need to
try the following cmake command:

cmake -DCAFFE_CPU_ONLY=True .

**Comment by marcoippolito** [comment] 2016-11-22 12:55
Hi,
i'm having the same problem. Ubuntu 16.04 and in Makefile.config I set:
# CPU-only switch (uncomment to build without GPU support).
CPU_ONLY := 1
and tried different options (without solving it) for BLAS option:
BLAS := atlas
BLAS_LIB := /usr/lib/libatlas.so

or 
BLAS := open
BLAS_LIB := /usr/lib/libopenblas.so

Any suggestions?

**Comment by mhauskn** [comment] 2016-11-22 18:04
I'm assuming the issue is: cublas_v2.h: No such file or directory.

Can you try locate cublas_v2.h to make sure the file exists? If it exists, try adding the path to your $CPLUS_INCLUDE_PATH

**Comment by marcoippolito** [comment] 2016-11-22 18:27
Hi,
thanks for helping:

marco@marco:~$ locate cublas_v2.h
/opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include/cublas_v2.h
marco@marco:~$ export CPLUS_INCLUDE_PATH=/opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include/cublas_v2.h

Makefile.config : 
# uncomment to disable IO dependencies and corresponding data layers
USE_OPENCV := 0

# CUDA directory contains bin/ and lib/ directories that we need.
#CUDA_DIR := /usr/local/cuda
#CUDA_DIR := /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/lib
CUDA_DIR := /opt/disco_vecchio/usr/local/cuda-7.5/
# For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
                -gencode arch=compute_20,code=sm_21 \
                -gencode arch=compute_30,code=sm_30 \
                -gencode arch=compute_35,code=sm_35 \
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_50,code=compute_50
# open for OpenBlas
BLAS := atlas
#BLAS := open
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas
#BLAS_LIB := /usr/lib/libopenblas.so
#BLAS_LIB := /usr/lib/openblas-base/libblas.so
BLAS_LIB := /usr/lib/libatlas.so

marco@marco:~/caffe-master$ mkdir build
marco@marco:~/caffe-master$ cd build
marco@marco:~/caffe-master/build$ cmake -DCAFFE_CPU_ONLY=True ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16")
-- Found LMDB: /usr/include
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB: /usr/include
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
CMake Warning at cmake/Dependencies.cmake:63 (message):
  -- CUDA is not detected by cmake.  Building without it...
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)


-- OpenCV found (/usr/share/OpenCV)
-- Found Atlas: /usr/include
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.7")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2.7")
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.11.0", minimum required is "1.7.1")
-- NumPy ver. 1.11.0 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found Git: /usr/bin/git (found version "2.7.4")
--
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   unknown
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   lmdb              :   Yes (ver. 0.9.17)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 2.4.9.1)
--   CUDA              :   No
--
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.12)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.12)
--   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)
--
-- Documentaion:
--   Doxygen           :   No
--   config_file       :
--
-- Install:
--   Install path      :   /home/marco/caffe-master/build/install
--
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CAFFE_CPU_ONLY

So...first question is: why CPU_ONLY          :   OFF ?

marco@marco:~/caffe-master/build$ make -j4
[  0%] Running C++/Python protocol buffer compiler on /home/marco/caffe-master/src/caffe/proto/caffe.proto
[100%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/marco/caffe-master/python/caffe/_caffe.so -> /home/marco/caffe-master/build/lib/_caffe.so
[100%] Built target pycaffe

marco@marco:~/caffe-master/build$ sudo make install
[  1%] Built target proto
-- Set runtime path of "/home/marco/caffe-master/build/install/python/caffe/_caffe.so" to "/home/marco/caffe-master/build/install/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib"
marco@marco:~/caffe-master/build$

firstCaffe.cpp : 
#include <iostream>
#include <caffe/caffe.hpp>
#include <caffe/util/io.hpp>
#include <caffe/blob.hpp>

//#define CPU_ONLY

int main() {

  return 0;
}

marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include firstCaffe.cpp -ofirstCaffe
In file included from /home/marco/caffe-master/include/caffe/common.hpp:19:0,
                 from /home/marco/caffe-master/include/caffe/blob.hpp:8,
                 from /home/marco/caffe-master/include/caffe/caffe.hpp:7,
                 from firstCaffe.cpp:2:
/home/marco/caffe-master/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory
compilation terminated.

**Comment by mhauskn** [comment] 2016-11-22 18:35
Try:

export CPLUS_INCLUDE_PATH=/opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include/

also try:

g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe

**Comment by marcoippolito** [comment] 2016-11-22 18:43
After:
1)doing export CPLUS_INCLUDE_PATH=/opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include/
2) removing the "old" build dir  and compiling within a new one (cmake.. -> make -j4 -> sudo make install)
marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe
In file included from /home/marco/caffe-master/include/caffe/caffe.hpp:7:0,
                 from firstCaffe.cpp:2:
/home/marco/caffe-master/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.

**Comment by mhauskn** [comment] 2016-11-22 18:50
Symlink the built proto files.

cd your_caffe_dir/include/caffe
ln -s ../../.build_release/src/caffe/proto/ .

**Comment by marcoippolito** [comment] 2016-11-22 18:59
marco@marco:~/caffe-master/include/caffe$ ln -s ../../.build_release/src/caffe/proto/ .
marco@marco:~/caffe-master/include/caffe$

marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe
In file included from /home/marco/caffe-master/include/caffe/caffe.hpp:7:0,
                 from firstCaffe.cpp:2:
/home/marco/caffe-master/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.
Just to check that the symlink is there:
marco@marco:~/caffe-master/include/caffe$ ln -s ../../.build_release/src/caffe/proto/ .
ln: failed to create symbolic link './proto': File exists

(Sorry for the "strange" formatting of this text)
So I've done the symlink but still doesn't find caffe.pb.h

**Comment by mhauskn** [comment] 2016-11-22 19:27
It's still not finding your caffe.pb.h file. You need to make sure caffe.pb.h is in your /home/marco/caffe-master/include/caffe/proto/ directory. Symlink or copy the file there.

**Comment by marcoippolito** [comment] 2016-11-22 19:40
marco@marco:~/caffe-master/include/caffe$ mkdir proto
marco@marco:~/caffe-master/include/caffe$ cd proto
marco@marco:~/caffe-master/include/caffe/proto$ ln -s ../../.build_release/src/caffe/proto/ .
marco@marco:~/caffe-master/include/caffe/proto$ ls -lah
total 8.0K
drwxrwxr-x 2 marco marco 4.0K Nov 22 20:37 .
drwxrwxr-x 6 marco marco 4.0K Nov 22 20:36 ..
lrwxrwxrwx 1 marco marco   37 Nov 22 20:37 proto -> ../../.build_release/src/caffe/proto/
marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe
In file included from /home/marco/caffe-master/include/caffe/caffe.hpp:7:0,
                 from firstCaffe.cpp:2:
/home/marco/caffe-master/include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.

marco@marco:~/caffe-master$ find -name "caffe.pb.h"
./build/install/include/caffe/proto/caffe.pb.h
./build/include/caffe/proto/caffe.pb.h
marco@marco:~/caffe-master$ cp -i ./build/install/include/caffe/proto/caffe.pb.h /home/marco/caffe-master/include/caffe/proto/caffe.pb.h
marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe
/tmp/ccrHBIT2.o: In function `_GLOBAL__sub_I_main':
firstCaffe.cpp:(.text.startup+0x33): undefined reference to `boost::system::generic_category()'
firstCaffe.cpp:(.text.startup+0x38): undefined reference to `boost::system::generic_category()'
firstCaffe.cpp:(.text.startup+0x41): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status

marco@marco:~/caffe-master$ cp -i ./build/include/caffe/proto/caffe.pb.h /home/marco/caffe-master/include/caffe/proto/caffe.pb.h
cp: overwrite '/home/marco/caffe-master/include/caffe/proto/caffe.pb.h'? y
marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe
/tmp/cc2anJIn.o: In function `_GLOBAL__sub_I_main':
firstCaffe.cpp:(.text.startup+0x33): undefined reference to `boost::system::generic_category()'
firstCaffe.cpp:(.text.startup+0x38): undefined reference to `boost::system::generic_category()'
firstCaffe.cpp:(.text.startup+0x41): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status

**Comment by mhauskn** [comment] 2016-11-22 19:43
sudo apt-get install libboost-dev

**Comment by marcoippolito** [comment] 2016-11-22 19:43
marco@marco:~/caffe-master$ sudo apt-get install libboost-dev
[sudo] password for marco:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-dev is already the newest version (1.58.0.1ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 5 not to upgrade.

**Comment by mhauskn** [comment] 2016-11-22 19:46
g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -ofirstCaffe -lboost_system -lboost_filesystem


Note that is an "L" not an "I"

**Comment by marcoippolito** [comment] 2016-11-22 19:48
yes...I was just writing you that now it is ok. 👍 marco@marco:~/caffe-master/examples/prove$ g++ -Wno-unused-result -O3 -std=c++11 -I /home/marco/caffe-master/include -I /opt/disco_vecchio/usr/local/cuda-7.5/targets/x86_64-linux/include firstCaffe.cpp -lboost_system -ofirstCaffe
marco@marco:~/caffe-master/examples/prove$ ./firstCaffe
marco@marco:~/caffe-master/examples/prove$

Thank you very for your kind help Matthew!!!
Cheers from Italy
Marco

**Comment by mhauskn** [comment] 2016-11-22 19:48
Cheers

**Closed as completed by mhauskn** 2016-11-22 19:48 UTC

**Comment by qjqjqjj** [comment] 2017-10-19 07:51
Hi, while I was installing caffe on my jetson tx2 card. I had the same issue, after I tried to locate cublas_v2.h. it's show that I don't have that file. So where can I install it? 

P.S im building it with GPU support
